### ISSUE TITLE
I get a make check error

### ISSUE THREAD

**Issue by josheeg** [willsq/tf-DNC#1]
joshua@joshua-HP-ENVY-m7-Notebook:~/Downloads/tf-DNC-master$ make check
pycodestyle --max-line-length=100 dnc
make: pycodestyle: Command not found
Makefile:8: recipe for target 'check' failed
make: *** [check] Error 127

then make test error that probably is a continuation
joshua@joshua-HP-ENVY-m7-Notebook:~/Downloads/tf-DNC-master$ make test
pycodestyle --max-line-length=100 dnc
make: pycodestyle: Command not found
Makefile:8: recipe for target 'check' failed
make: *** [check] Error 127

again vis error so probably a continuation
joshua@joshua-HP-ENVY-m7-Notebook:~/Downloads/tf-DNC-master$ make vis
make: *** No rule to make target 'vis'.  Stop.

basic usage error
joshua@joshua-HP-ENVY-m7-Notebook:~/Downloads/tf-DNC-master$ make test
pycodestyle --max-line-length=100 dnc
make: pycodestyle: Command not found
Makefile:8: recipe for target 'check' failed
make: *** [check] Error 127

**Comment by willsq** [comment]
If you run `make deps` first you should be able to run `make check` cleanly
